# Generated by Django 2.1.7 on 2019-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190215_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG_Slices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_field', models.ImageField(null=True, upload_to='crop')),
            ],
        ),
        migrations.RemoveField(
            model_name='img',
            name='img_url',
        ),
        migrations.AddField(
            model_name='img',
            name='img_field',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
