# Generated by Django 2.1.7 on 2019-02-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190218_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='img_field',
            new_name='img_origin',
        ),
        migrations.AddField(
            model_name='img',
            name='nx',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='img',
            name='ny',
            field=models.IntegerField(null=True),
        ),
    ]
