# Generated by Django 2.1.7 on 2019-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190218_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slice',
            name='img_slice',
            field=models.ImageField(null=True, upload_to='slices'),
        ),
    ]
