# Generated by Django 2.1.7 on 2019-02-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190218_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slice',
            old_name='result',
            new_name='results',
        ),
    ]
