# Generated by Django 2.1.5 on 2019-02-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_img_slice_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='result0',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
