# Generated by Django 2.1.5 on 2019-02-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190219_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slice',
            old_name='results',
            new_name='result_text',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='result0',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='result2',
        ),
    ]
