# Generated by Django 2.1.5 on 2019-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_slice_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='result0',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result2',
            field=models.FloatField(null=True),
        ),
    ]
