# Generated by Django 2.1.5 on 2019-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190223_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='result0txt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result1txt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slice',
            name='result2txt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
